[package]
name = "notes"
version = "0.1.0"
edition = "2024"


[dependencies]
chrono = "0.4.42"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = { version = "4", features = ["derive"] }
comfy-table = "7.2.1"
color-print = "0.3.7"
